### ISSUE TITLE
Cucumber sandwich not showing screenshots from json

### ISSUE THREAD

**Issue by hanikad** [damianszczepanik/cucumber-sandwich#34]
Hi This is my json. I am cucumber sandwich jar to generate report.My html report is not showing image when step failed..

I have added a image in step definition.

[Droid_Automation_report.txt](https://github.com/damianszczepanik/cucumber-sandwich/files/729222/Droid_Automation_report.txt)

**Comment by damianszczepanik** [comment]
This is because @after is inside the steps but should be with scenario. Looks like this is not valid json report

**Comment by hanikad** [comment]
Hi Damian ,

I have some image validation in steps.

So i want to insert image @afterstep .

Hanika D
Senior Consultant
Email hanikad@thoughtworks.com
Telephone 9821795843
[image: ThoughtWorks]
<http://www.thoughtworks.com/?utm_campaign=hanika-d-signature&utm_medium=email&utm_source=thoughtworks-email-signature-generator>

On Thu, Jan 26, 2017 at 2:25 AM, Damian Szczepanik <notifications@github.com

**Comment by damianszczepanik** [comment]
Keep cucumber standard, then report will work fine

**Comment by jiten0811** [comment]
Hi Daminan,

Please find my JSON attached, i am seeing the screenshot being embed into Index.html , but not to HTML generated via Sandwich Jar2.1V, could you please let me know me there is anything i need to do extra in order to have it attached to my HTML report .

[SnapshotIssue.txt](https://github.com/damianszczepanik/cucumber-sandwich/files/3000180/SnapshotIssue.txt)

**Comment by damianszczepanik** [comment]
2.1 is very old, upgrade and try again
